import Head from "next/head";
import { Container } from "@chakra-ui/react";
import Image from "next/image";
import CallToActionWithAnnotation from "../components/CallToActionWithAnnotation";
import LargeWithLogoCentered from "../components/LargeWithLogoCentered";
import WithSubNavigation from "../components/navbar/WithSubNavigation";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <WithSubNavigation />
      <CallToActionWithAnnotation />

      <Container>
        <main>
          <h1>
            Welcome to <a href="https://nextjs.org">Next.js!</a>
          </h1>
          <p>this is main</p>
        </main>
      </Container>

      <footer>
        <LargeWithLogoCentered />
      </footer>
    </>
  );
}
